// src/components/index.ts
export { default as ActiveSection } from './ActiveSection'
export { default as FooterSection } from './FooterSection'
export { default as Hero } from './Hero'
export { default as Logout } from './Logout'
export { default as Navbar } from './Navbar'
export { ProtectedRoute, ProtectedRegistrationRoute } from './ProtectedRoute'
export { default as RegistrationForm } from './RegistrationForm'
export { default as Services } from './Services'
export { default as SubcribeSection } from './SubcribeSection'
export { default as Testimonials } from './Testimonials'
export { default as ThemeToggle } from './theme-toggle'
export { default as Trainers } from './Trainers'
